# Generated by Django 3.2.9 on 2021-11-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMarketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=50)),
        ),
        migrations.AddField(
            model_name='fabricante',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=20)),
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=60)),
        ),
    ]
