# Generated by Django 3.2.8 on 2022-01-11 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMarketplace', '0003_auto_20211110_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.FloatField()),
                ('username', models.CharField(max_length=30)),
                ('texto', models.CharField(max_length=250)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMarketplace.producto')),
            ],
        ),
    ]
